extern u64 gMollyNpcSkel_belt_ci8_ci8[];
extern u64 gMollyNpcSkel_belt_ci8_pal_rgba16[];
extern u64 gMollyNpcSkel_gibdo_wrapping_rgba16_png_001_rgba16[];
extern u64 gMollyNpcSkel_blue_leaf_floor_rgba16[];
extern u64 gMollyNpcSkel_red_carpet_ci8[];
extern u64 gMollyNpcSkel_red_carpet_pal_rgba16[];
extern u64 gMollyNpcSkel_ripped_shirt_rgba16[];
extern u64 gMollyNpcSkel_nipple_ci8[];
extern u64 gMollyNpcSkel_nipple_pal_rgba16[];
extern u64 gMollyNpcSkel_nose_rgba16_ci4[];
extern u64 gMollyNpcSkel_nose_rgba16_pal_rgba16[];
extern u64 gMollyNpcSkel_hair_ci8_ci8[];
extern u64 gMollyNpcSkel_hair_ci8_pal_rgba16[];
extern u64 gMollyNpcSkel_gibdo_eye_rgba16_png_001_rgba16[];
extern u64 gMollyNpcSkel_eye_open_ci8_ci8[];
extern u64 gMollyNpcSkel_eye_open_ci8_pal_rgba16[];
extern Vtx gMollyNpcSkel_root_mesh_layer_Opaque_vtx_0[23];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_root_mesh_layer_Opaque_vtx_1[42];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_root_mesh_layer_Opaque_vtx_2[4];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_root_mesh_layer_Opaque_vtx_3[13];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque_tri_3[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_0[6];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_1[38];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_2[5];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_booba_mesh_layer_Opaque_vtx_0[38];
extern Gfx gMollyNpcSkel_booba_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_booba_mesh_layer_Opaque_vtx_1[8];
extern Gfx gMollyNpcSkel_booba_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_booba_mesh_layer_Opaque_vtx_2[10];
extern Gfx gMollyNpcSkel_booba_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_neck_mesh_layer_Opaque_vtx_0[7];
extern Gfx gMollyNpcSkel_neck_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_neck_mesh_layer_Opaque_vtx_1[20];
extern Gfx gMollyNpcSkel_neck_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_0[56];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_1[13];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_2[70];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_3[100];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_3[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_4[8];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_4[];
extern Vtx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_vtx_0[13];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_vtx_1[8];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_vtx_2[7];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque_vtx_1[16];
extern Gfx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_forearm_L_mesh_layer_Opaque_vtx_0[10];
extern Gfx gMollyNpcSkel_forearm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_forearm_L_mesh_layer_Opaque_vtx_1[4];
extern Gfx gMollyNpcSkel_forearm_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_hand_L_mesh_layer_Opaque_vtx_0[30];
extern Gfx gMollyNpcSkel_hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_vtx_0[23];
extern Gfx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_upper_arm_R_mesh_layer_Opaque_vtx_0[21];
extern Gfx gMollyNpcSkel_upper_arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_forearm_R_mesh_layer_Opaque_vtx_0[18];
extern Gfx gMollyNpcSkel_forearm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_hand_R_mesh_layer_Opaque_vtx_0[25];
extern Gfx gMollyNpcSkel_hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_waist_L_mesh_layer_Opaque_vtx_0[9];
extern Gfx gMollyNpcSkel_waist_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_thigh_L_mesh_layer_Opaque_vtx_0[42];
extern Gfx gMollyNpcSkel_thigh_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shin_L_mesh_layer_Opaque_vtx_0[51];
extern Gfx gMollyNpcSkel_shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_foot_L_mesh_layer_Opaque_vtx_0[24];
extern Gfx gMollyNpcSkel_foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_waist_R_mesh_layer_Opaque_vtx_0[15];
extern Gfx gMollyNpcSkel_waist_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_thigh_R_mesh_layer_Opaque_vtx_0[45];
extern Gfx gMollyNpcSkel_thigh_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shin_R_mesh_layer_Opaque_vtx_0[51];
extern Gfx gMollyNpcSkel_shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_foot_R_mesh_layer_Opaque_vtx_0[24];
extern Gfx gMollyNpcSkel_foot_R_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gMollyNpcSkel_belt_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_f3dlite_material_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_jeans_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_shirt_material_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_shirt_ripped_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_nipple_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_skin_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_hair_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_f3dlite_material_002_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_eyes_layerOpaque[];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_booba_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_neck_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_forearm_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_hand_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_upper_arm_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_forearm_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_hand_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_waist_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_thigh_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shin_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_foot_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_waist_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_thigh_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shin_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_foot_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gMollyNpcSkel;
extern AnimationHeader gMollyNpcIdleAnim;
#define GMOLLYNPCSKEL_ROOT_POS_LIMB 0
#define GMOLLYNPCSKEL_ROOT_ROT_LIMB 1
#define GMOLLYNPCSKEL_MIDDLE_BACK_LIMB 2
#define GMOLLYNPCSKEL_BOOBA_LIMB 3
#define GMOLLYNPCSKEL_NECK_LIMB 4
#define GMOLLYNPCSKEL_HEAD_LIMB 5
#define GMOLLYNPCSKEL_SHOULDER_L_LIMB 6
#define GMOLLYNPCSKEL_UPPER_ARM_L_LIMB 7
#define GMOLLYNPCSKEL_FOREARM_L_LIMB 8
#define GMOLLYNPCSKEL_HAND_L_LIMB 9
#define GMOLLYNPCSKEL_SHOULDER_R_LIMB 10
#define GMOLLYNPCSKEL_UPPER_ARM_R_LIMB 11
#define GMOLLYNPCSKEL_FOREARM_R_LIMB 12
#define GMOLLYNPCSKEL_HAND_R_LIMB 13
#define GMOLLYNPCSKEL_WAIST_L_LIMB 14
#define GMOLLYNPCSKEL_THIGH_L_LIMB 15
#define GMOLLYNPCSKEL_SHIN_L_LIMB 16
#define GMOLLYNPCSKEL_FOOT_L_LIMB 17
#define GMOLLYNPCSKEL_WAIST_R_LIMB 18
#define GMOLLYNPCSKEL_THIGH_R_LIMB 19
#define GMOLLYNPCSKEL_SHIN_R_LIMB 20
#define GMOLLYNPCSKEL_FOOT_R_LIMB 21
#define GMOLLYNPCSKEL_NUM_LIMBS 22
