extern u64 gMollyNpcSkel_ab_armour_rgba16[];
extern u64 gMollyNpcSkel_Pomnitextura_ci8[];
extern u64 gMollyNpcSkel_Pomnitextura_pal_rgba16[];
extern u64 gMollyNpcSkel_nose_rgba16_ci4[];
extern u64 gMollyNpcSkel_nose_rgba16_pal_rgba16[];
extern u64 gMollyNpcSkel_nipple_ci8[];
extern u64 gMollyNpcSkel_nipple_pal_rgba16[];
extern u64 gMollyNpcSkel_cleavage_ci4[];
extern u64 gMollyNpcSkel_cleavage_pal_rgba16[];
extern u64 gMollyNpcSkel_triangle_armour_ci8[];
extern u64 gMollyNpcSkel_triangle_armour_pal_rgba16[];
extern u64 gMollyNpcSkel_belt_ci8_ci8[];
extern u64 gMollyNpcSkel_belt_ci8_pal_rgba16[];
extern u64 gMollyNpcSkel_mouth_neutral_ci8_ci8[];
extern u64 gMollyNpcSkel_mouth_neutral_ci8_pal_rgba16[];
extern u64 gMollyNpcSkel_eye_open_ci8_ci8[];
extern u64 gMollyNpcSkel_eye_open_ci8_pal_rgba16[];
extern u64 gMollyNpcSkel_hair_ci8_ci8[];
extern u64 gMollyNpcSkel_hair_ci8_pal_rgba16[];
extern u64 gMollyNpcSkel_hilite_1_rgba16_png_001_rgba16[];
extern u64 gMollyNpcSkel_sword_guard_ci8_png_001_ci8[];
extern u64 gMollyNpcSkel_sword_guard_ci8_png_001_pal_rgba16[];
extern u64 gMollyNpcSkel_sword_emblem_ci8_png_001_ci8[];
extern u64 gMollyNpcSkel_sword_emblem_ci8_png_001_pal_rgba16[];
extern u64 gMollyNpcSkel_sword_pommel_ci8_png_001_ci8[];
extern u64 gMollyNpcSkel_sword_pommel_ci8_png_001_pal_rgba16[];
extern u64 gMollyNpcSkel_arm_gauntlet_ci8_ci8[];
extern u64 gMollyNpcSkel_arm_gauntlet_ci8_pal_rgba16[];
extern u64 gMollyNpcSkel_back_armour_ci8[];
extern u64 gMollyNpcSkel_back_armour_pal_rgba16[];
extern Vtx gMollyNpcSkel_root_mesh_layer_Opaque_vtx_0[27];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_root_mesh_layer_Opaque_vtx_1[8];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_0[35];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_1[12];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_2[18];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_3[5];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_3[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_4[8];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_4[];
extern Vtx gMollyNpcSkel_middle_back_mesh_layer_Opaque_vtx_5[12];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque_tri_5[];
extern Vtx gMollyNpcSkel_booba_L_mesh_layer_Opaque_vtx_0[28];
extern Gfx gMollyNpcSkel_booba_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_booba_L_mesh_layer_Opaque_vtx_1[9];
extern Gfx gMollyNpcSkel_booba_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_booba_L_mesh_layer_Opaque_vtx_2[20];
extern Gfx gMollyNpcSkel_booba_L_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_booba_L_mesh_layer_Opaque_vtx_3[7];
extern Gfx gMollyNpcSkel_booba_L_mesh_layer_Opaque_tri_3[];
extern Vtx gMollyNpcSkel_booba_L_mesh_layer_Opaque_vtx_4[9];
extern Gfx gMollyNpcSkel_booba_L_mesh_layer_Opaque_tri_4[];
extern Vtx gMollyNpcSkel_booba_R_mesh_layer_Opaque_vtx_0[28];
extern Gfx gMollyNpcSkel_booba_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_booba_R_mesh_layer_Opaque_vtx_1[9];
extern Gfx gMollyNpcSkel_booba_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_booba_R_mesh_layer_Opaque_vtx_2[13];
extern Gfx gMollyNpcSkel_booba_R_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_booba_R_mesh_layer_Opaque_vtx_3[21];
extern Gfx gMollyNpcSkel_booba_R_mesh_layer_Opaque_tri_3[];
extern Vtx gMollyNpcSkel_booba_R_mesh_layer_Opaque_vtx_4[7];
extern Gfx gMollyNpcSkel_booba_R_mesh_layer_Opaque_tri_4[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_0[63];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_1[7];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_2[15];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_3[157];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_3[];
extern Vtx gMollyNpcSkel_head_mesh_layer_Opaque_vtx_4[250];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque_tri_4[];
extern Vtx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_vtx_1[34];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_vtx_2[14];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque_vtx_0[81];
extern Gfx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_forearm_L_mesh_layer_Opaque_vtx_0[24];
extern Gfx gMollyNpcSkel_forearm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_hand_L_mesh_layer_Opaque_vtx_0[29];
extern Gfx gMollyNpcSkel_hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_hand_L_mesh_layer_Opaque_vtx_1[15];
extern Gfx gMollyNpcSkel_hand_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_sword_mesh_layer_Opaque_vtx_0[82];
extern Gfx gMollyNpcSkel_sword_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_sword_mesh_layer_Opaque_vtx_1[89];
extern Gfx gMollyNpcSkel_sword_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_sword_mesh_layer_Opaque_vtx_2[18];
extern Gfx gMollyNpcSkel_sword_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_sword_mesh_layer_Opaque_vtx_3[29];
extern Gfx gMollyNpcSkel_sword_mesh_layer_Opaque_tri_3[];
extern Vtx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_vtx_0[5];
extern Gfx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_vtx_1[39];
extern Gfx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_vtx_2[11];
extern Gfx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque_tri_2[];
extern Vtx gMollyNpcSkel_upper_arm_R_mesh_layer_Opaque_vtx_0[80];
extern Gfx gMollyNpcSkel_upper_arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_forearm_R_mesh_layer_Opaque_vtx_0[25];
extern Gfx gMollyNpcSkel_forearm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_forearm_R_mesh_layer_Opaque_vtx_1[4];
extern Gfx gMollyNpcSkel_forearm_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_hand_R_mesh_layer_Opaque_vtx_0[30];
extern Gfx gMollyNpcSkel_hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_hand_R_mesh_layer_Opaque_vtx_1[14];
extern Gfx gMollyNpcSkel_hand_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_waist_L_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMollyNpcSkel_waist_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_waist_L_mesh_layer_Opaque_vtx_1[28];
extern Gfx gMollyNpcSkel_waist_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_thigh_L_mesh_layer_Opaque_vtx_0[103];
extern Gfx gMollyNpcSkel_thigh_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shin_L_mesh_layer_Opaque_vtx_0[26];
extern Gfx gMollyNpcSkel_shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_foot_L_mesh_layer_Opaque_vtx_0[45];
extern Gfx gMollyNpcSkel_foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_foot_L_mesh_layer_Opaque_vtx_1[19];
extern Gfx gMollyNpcSkel_foot_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_waist_R_mesh_layer_Opaque_vtx_0[10];
extern Gfx gMollyNpcSkel_waist_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_waist_R_mesh_layer_Opaque_vtx_1[29];
extern Gfx gMollyNpcSkel_waist_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_thigh_R_mesh_layer_Opaque_vtx_0[120];
extern Gfx gMollyNpcSkel_thigh_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shin_R_mesh_layer_Opaque_vtx_0[22];
extern Gfx gMollyNpcSkel_shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_shin_R_mesh_layer_Opaque_vtx_1[15];
extern Gfx gMollyNpcSkel_shin_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMollyNpcSkel_foot_R_mesh_layer_Opaque_vtx_0[30];
extern Gfx gMollyNpcSkel_foot_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMollyNpcSkel_foot_R_mesh_layer_Opaque_vtx_1[10];
extern Gfx gMollyNpcSkel_foot_R_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gMollyNpcSkel_ab_armour_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_outfit_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_skin_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_nipple_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_cleavage_skin_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_armour_triangle_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_belt_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_mouth_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_eyes_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_hair_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_f3dlite_material_001_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_f3dlite_material_003_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_f3dlite_material_004_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_f3dlite_material_002_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_shoes_layerOpaque[];
extern Gfx mat_gMollyNpcSkel_back_armour_layerOpaque[];
extern Gfx gMollyNpcSkel_root_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_middle_back_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_booba_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_booba_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_head_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shoulder_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_upper_arm_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_forearm_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_hand_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_sword_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shoulder_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_upper_arm_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_forearm_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_hand_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_waist_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_thigh_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shin_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_foot_L_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_waist_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_thigh_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_shin_R_mesh_layer_Opaque[];
extern Gfx gMollyNpcSkel_foot_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gMollyNpcSkel;
extern AnimationHeader gMollyNpcWalkAnim;
extern AnimationHeader gMollyNpcIdleAnim;
#define GMOLLYNPCSKEL_ROOT_POS_LIMB 0
#define GMOLLYNPCSKEL_ROOT_ROT_LIMB 1
#define GMOLLYNPCSKEL_MIDDLE_BACK_LIMB 2
#define GMOLLYNPCSKEL_BOOBA_L_LIMB 3
#define GMOLLYNPCSKEL_BOOBA_R_LIMB 4
#define GMOLLYNPCSKEL_HEAD_LIMB 5
#define GMOLLYNPCSKEL_SHOULDER_L_LIMB 6
#define GMOLLYNPCSKEL_UPPER_ARM_L_LIMB 7
#define GMOLLYNPCSKEL_FOREARM_L_LIMB 8
#define GMOLLYNPCSKEL_HAND_L_LIMB 9
#define GMOLLYNPCSKEL_SWORD_LIMB 10
#define GMOLLYNPCSKEL_SHOULDER_R_LIMB 11
#define GMOLLYNPCSKEL_UPPER_ARM_R_LIMB 12
#define GMOLLYNPCSKEL_FOREARM_R_LIMB 13
#define GMOLLYNPCSKEL_HAND_R_LIMB 14
#define GMOLLYNPCSKEL_WAIST_L_LIMB 15
#define GMOLLYNPCSKEL_THIGH_L_LIMB 16
#define GMOLLYNPCSKEL_SHIN_L_LIMB 17
#define GMOLLYNPCSKEL_FOOT_L_LIMB 18
#define GMOLLYNPCSKEL_WAIST_R_LIMB 19
#define GMOLLYNPCSKEL_THIGH_R_LIMB 20
#define GMOLLYNPCSKEL_SHIN_R_LIMB 21
#define GMOLLYNPCSKEL_FOOT_R_LIMB 22
#define GMOLLYNPCSKEL_NUM_LIMBS 23
