extern u64 gMilkLadySkel_nose_rgba16_ci4[];
extern u64 gMilkLadySkel_nose_rgba16_pal_rgba16[];
extern u64 gMilkLadySkel_nipple_ci8[];
extern u64 gMilkLadySkel_nipple_pal_rgba16[];
extern u64 gMilkLadySkel_mouth_neutral_ci8_ci8[];
extern u64 gMilkLadySkel_mouth_neutral_ci8_pal_rgba16[];
extern u64 gMilkLadySkel_eye_open_ci8_ci8[];
extern u64 gMilkLadySkel_eye_open_ci8_pal_rgba16[];
extern u64 gMilkLadySkel_hair_ci8_ci8[];
extern u64 gMilkLadySkel_hair_ci8_pal_rgba16[];
extern u64 gMilkLadySkel_arm_gauntlet_ci8_ci8[];
extern u64 gMilkLadySkel_arm_gauntlet_ci8_pal_rgba16[];
extern Vtx gMilkLadySkel_root_mesh_layer_Opaque_vtx_0[36];
extern Gfx gMilkLadySkel_root_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_middle_back_mesh_layer_Opaque_vtx_0[20];
extern Gfx gMilkLadySkel_middle_back_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_booba_L_mesh_layer_Opaque_vtx_0[18];
extern Gfx gMilkLadySkel_booba_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_booba_L_mesh_layer_Opaque_vtx_1[7];
extern Gfx gMilkLadySkel_booba_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkLadySkel_booba_R_mesh_layer_Opaque_vtx_0[7];
extern Gfx gMilkLadySkel_booba_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_booba_R_mesh_layer_Opaque_vtx_1[18];
extern Gfx gMilkLadySkel_booba_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkLadySkel_head_mesh_layer_Opaque_vtx_0[61];
extern Gfx gMilkLadySkel_head_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_head_mesh_layer_Opaque_vtx_1[7];
extern Gfx gMilkLadySkel_head_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkLadySkel_head_mesh_layer_Opaque_vtx_2[14];
extern Gfx gMilkLadySkel_head_mesh_layer_Opaque_tri_2[];
extern Vtx gMilkLadySkel_head_mesh_layer_Opaque_vtx_3[159];
extern Gfx gMilkLadySkel_head_mesh_layer_Opaque_tri_3[];
extern Vtx gMilkLadySkel_shoulder_L_mesh_layer_Opaque_vtx_0[18];
extern Gfx gMilkLadySkel_shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_upper_arm_L_mesh_layer_Opaque_vtx_0[27];
extern Gfx gMilkLadySkel_upper_arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_forearm_L_mesh_layer_Opaque_vtx_0[22];
extern Gfx gMilkLadySkel_forearm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_hand_L_mesh_layer_Opaque_vtx_0[23];
extern Gfx gMilkLadySkel_hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_shoulder_R_mesh_layer_Opaque_vtx_0[18];
extern Gfx gMilkLadySkel_shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_upper_arm_R_mesh_layer_Opaque_vtx_0[21];
extern Gfx gMilkLadySkel_upper_arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_forearm_R_mesh_layer_Opaque_vtx_0[21];
extern Gfx gMilkLadySkel_forearm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_hand_R_mesh_layer_Opaque_vtx_0[30];
extern Gfx gMilkLadySkel_hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_waist_L_mesh_layer_Opaque_vtx_0[27];
extern Gfx gMilkLadySkel_waist_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_thigh_L_mesh_layer_Opaque_vtx_0[54];
extern Gfx gMilkLadySkel_thigh_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_shin_L_mesh_layer_Opaque_vtx_0[26];
extern Gfx gMilkLadySkel_shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_foot_L_mesh_layer_Opaque_vtx_0[45];
extern Gfx gMilkLadySkel_foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_foot_L_mesh_layer_Opaque_vtx_1[19];
extern Gfx gMilkLadySkel_foot_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkLadySkel_waist_R_mesh_layer_Opaque_vtx_0[25];
extern Gfx gMilkLadySkel_waist_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_thigh_R_mesh_layer_Opaque_vtx_0[62];
extern Gfx gMilkLadySkel_thigh_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_shin_R_mesh_layer_Opaque_vtx_0[25];
extern Gfx gMilkLadySkel_shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_foot_R_mesh_layer_Opaque_vtx_0[43];
extern Gfx gMilkLadySkel_foot_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkLadySkel_foot_R_mesh_layer_Opaque_vtx_1[19];
extern Gfx gMilkLadySkel_foot_R_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gMilkLadySkel_skin_layerOpaque[];
extern Gfx mat_gMilkLadySkel_nipple_layerOpaque[];
extern Gfx mat_gMilkLadySkel_mouth_layerOpaque[];
extern Gfx mat_gMilkLadySkel_eyes_layerOpaque[];
extern Gfx mat_gMilkLadySkel_hair_layerOpaque[];
extern Gfx mat_gMilkLadySkel_shoes_layerOpaque[];
extern Gfx gMilkLadySkel_root_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_middle_back_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_booba_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_booba_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_head_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_shoulder_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_upper_arm_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_forearm_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_hand_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_shoulder_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_upper_arm_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_forearm_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_hand_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_waist_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_thigh_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_shin_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_foot_L_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_waist_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_thigh_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_shin_R_mesh_layer_Opaque[];
extern Gfx gMilkLadySkel_foot_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gMilkLadySkel;
extern AnimationHeader gMilkLadySkelIdleAnim;
#define GMILKLADYSKEL_ROOT_POS_LIMB 0
#define GMILKLADYSKEL_ROOT_ROT_LIMB 1
#define GMILKLADYSKEL_MIDDLE_BACK_LIMB 2
#define GMILKLADYSKEL_BOOBA_L_LIMB 3
#define GMILKLADYSKEL_BOOBA_R_LIMB 4
#define GMILKLADYSKEL_HEAD_LIMB 5
#define GMILKLADYSKEL_SHOULDER_L_LIMB 6
#define GMILKLADYSKEL_UPPER_ARM_L_LIMB 7
#define GMILKLADYSKEL_FOREARM_L_LIMB 8
#define GMILKLADYSKEL_HAND_L_LIMB 9
#define GMILKLADYSKEL_SHOULDER_R_LIMB 10
#define GMILKLADYSKEL_UPPER_ARM_R_LIMB 11
#define GMILKLADYSKEL_FOREARM_R_LIMB 12
#define GMILKLADYSKEL_HAND_R_LIMB 13
#define GMILKLADYSKEL_WAIST_L_LIMB 14
#define GMILKLADYSKEL_THIGH_L_LIMB 15
#define GMILKLADYSKEL_SHIN_L_LIMB 16
#define GMILKLADYSKEL_FOOT_L_LIMB 17
#define GMILKLADYSKEL_WAIST_R_LIMB 18
#define GMILKLADYSKEL_THIGH_R_LIMB 19
#define GMILKLADYSKEL_SHIN_R_LIMB 20
#define GMILKLADYSKEL_FOOT_R_LIMB 21
#define GMILKLADYSKEL_NUM_LIMBS 22
