extern u64 gMilkMalonSkel_ab_armour_rgba16[];
extern u64 gMilkMalonSkel_cow_spotted_pattern_i8_i8[];
extern u64 gMilkMalonSkel_shirt_texture1_ci4[];
extern u64 gMilkMalonSkel_shirt_texture1_pal_rgba16[];
extern u64 gMilkMalonSkel_nose_rgba16_ci4[];
extern u64 gMilkMalonSkel_nose_rgba16_pal_rgba16[];
extern u64 gMilkMalonSkel_nose_rgba16_png_001_rgba16[];
extern u64 gMilkMalonSkel_gradient_rgba16_png_002_rgba16[];
extern u64 gMilkMalonSkel_eye_open_ci8_ci8[];
extern u64 gMilkMalonSkel_eye_open_ci8_pal_rgba16[];
extern u64 gMilkMalonSkel_mouth_neutral_ci8_ci8[];
extern u64 gMilkMalonSkel_mouth_neutral_ci8_pal_rgba16[];
extern u64 gMilkMalonSkel_hair_ci8_png_002_ci8[];
extern u64 gMilkMalonSkel_hair_ci8_png_002_pal_rgba16[];
extern u64 gMilkMalonSkel_ear_rgba16_png_002_rgba16[];
extern u64 gMilkMalonSkel_belt_ci8_ci8[];
extern u64 gMilkMalonSkel_belt_ci8_pal_rgba16[];
extern u64 gMilkMalonSkel_spot01_sceneTex_013B50_rgba16_ci8[];
extern u64 gMilkMalonSkel_spot01_sceneTex_013B50_rgba16_pal_rgba16[];
extern u64 gMilkMalonSkel_spot02_room_1Tex_014508_ci4_ci4[];
extern u64 gMilkMalonSkel_spot02_room_1Tex_014508_ci4_pal_rgba16[];
extern u64 gMilkMalonSkel_handle_jewel_ci8[];
extern u64 gMilkMalonSkel_handle_jewel_pal_rgba16[];
extern u64 gMilkMalonSkel_eff_unknown_12_i8_png_002_i8[];
extern u64 gMilkMalonSkel_object_gi_milkTex_000000_i8_png_001_i8[];
extern u64 gMilkMalonSkel_eff_unknown_12_i8_png_001_i8[];
extern u64 gMilkMalonSkel_metal_floor_rgba32[];
extern u64 gMilkMalonSkel_arm_gauntlet_ci8_ci8[];
extern u64 gMilkMalonSkel_arm_gauntlet_ci8_pal_rgba16[];
extern u64 gMilkMalonSkel_eff_unknown_12_i8_png_003_i8[];
extern u64 gMilkMalonSkel_eff_unknown_12_i8_png_004_i8[];
extern u64 gMilkMalonSkel_object_gi_milkTex_000000_i8_png_002_i8[];
extern u64 gMilkMalonSkel_Pomnitextura_ci8[];
extern u64 gMilkMalonSkel_Pomnitextura_pal_rgba16[];
extern u64 gMilkMalonSkel_back_armour_ci8[];
extern u64 gMilkMalonSkel_back_armour_pal_rgba16[];
extern u64 gMilkMalonSkel_arm_gauntlet_ci8_ci8_copy[];
extern u64 gMilkMalonSkel_arm_gauntlet_ci8_pal_rgba16_copy[];
extern Vtx gMilkMalonSkel_root_mesh_layer_Opaque_vtx_0[37];
extern Gfx gMilkMalonSkel_root_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_root_mesh_layer_Opaque_vtx_1[10];
extern Gfx gMilkMalonSkel_root_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_middle_back_mesh_layer_Opaque_vtx_0[47];
extern Gfx gMilkMalonSkel_middle_back_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_middle_back_mesh_layer_Opaque_vtx_1[4];
extern Gfx gMilkMalonSkel_middle_back_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_booba_L_mesh_layer_Opaque_vtx_0[73];
extern Gfx gMilkMalonSkel_booba_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_booba_R_mesh_layer_Opaque_vtx_0[82];
extern Gfx gMilkMalonSkel_booba_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_0[13];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_1[31];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_2[12];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_2[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_3[12];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_3[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_4[7];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_4[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_5[91];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_5[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_6[12];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_6[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_7[6];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_7[];
extern Vtx gMilkMalonSkel_head_mesh_layer_Opaque_vtx_8[6];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque_tri_8[];
extern Vtx gMilkMalonSkel_shoulder_L_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMilkMalonSkel_shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_shoulder_L_mesh_layer_Opaque_vtx_1[36];
extern Gfx gMilkMalonSkel_shoulder_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_shoulder_L_mesh_layer_Opaque_vtx_2[13];
extern Gfx gMilkMalonSkel_shoulder_L_mesh_layer_Opaque_tri_2[];
extern Vtx gMilkMalonSkel_upper_arm_L_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMilkMalonSkel_upper_arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_upper_arm_L_mesh_layer_Opaque_vtx_1[74];
extern Gfx gMilkMalonSkel_upper_arm_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_forearm_L_mesh_layer_Opaque_vtx_0[24];
extern Gfx gMilkMalonSkel_forearm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_hand_L_mesh_layer_Opaque_vtx_0[25];
extern Gfx gMilkMalonSkel_hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_hand_L_mesh_layer_Opaque_vtx_1[15];
extern Gfx gMilkMalonSkel_hand_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_hammer_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_hammer_mesh_layer_Opaque_vtx_1[30];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_hammer_mesh_layer_Opaque_vtx_2[24];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque_tri_2[];
extern Vtx gMilkMalonSkel_hammer_mesh_layer_Opaque_vtx_3[51];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque_tri_3[];
extern Vtx gMilkMalonSkel_hammer_mesh_layer_Opaque_vtx_4[48];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque_tri_4[];
extern Vtx gMilkMalonSkel_hammer_mesh_layer_Opaque_vtx_5[14];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque_tri_5[];
extern Vtx gMilkMalonSkel_hammer_mesh_layer_Opaque_vtx_6[182];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque_tri_6[];
extern Vtx gMilkMalonSkel_shoulder_R_mesh_layer_Opaque_vtx_0[5];
extern Gfx gMilkMalonSkel_shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_shoulder_R_mesh_layer_Opaque_vtx_1[42];
extern Gfx gMilkMalonSkel_shoulder_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_shoulder_R_mesh_layer_Opaque_vtx_2[11];
extern Gfx gMilkMalonSkel_shoulder_R_mesh_layer_Opaque_tri_2[];
extern Vtx gMilkMalonSkel_upper_arm_R_mesh_layer_Opaque_vtx_0[9];
extern Gfx gMilkMalonSkel_upper_arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_upper_arm_R_mesh_layer_Opaque_vtx_1[63];
extern Gfx gMilkMalonSkel_upper_arm_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_forearm_R_mesh_layer_Opaque_vtx_0[25];
extern Gfx gMilkMalonSkel_forearm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_forearm_R_mesh_layer_Opaque_vtx_1[4];
extern Gfx gMilkMalonSkel_forearm_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_hand_R_mesh_layer_Opaque_vtx_0[24];
extern Gfx gMilkMalonSkel_hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_hand_R_mesh_layer_Opaque_vtx_1[14];
extern Gfx gMilkMalonSkel_hand_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_cannon_mesh_layer_Opaque_vtx_0[153];
extern Gfx gMilkMalonSkel_cannon_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_cannon_mesh_layer_Opaque_vtx_1[48];
extern Gfx gMilkMalonSkel_cannon_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_cannon_mesh_layer_Opaque_vtx_2[34];
extern Gfx gMilkMalonSkel_cannon_mesh_layer_Opaque_tri_2[];
extern Vtx gMilkMalonSkel_cannon_mesh_layer_Opaque_vtx_3[18];
extern Gfx gMilkMalonSkel_cannon_mesh_layer_Opaque_tri_3[];
extern Vtx gMilkMalonSkel_cannon_mesh_layer_Opaque_vtx_4[24];
extern Gfx gMilkMalonSkel_cannon_mesh_layer_Opaque_tri_4[];
extern Vtx gMilkMalonSkel_cannon_mesh_layer_Opaque_vtx_5[16];
extern Gfx gMilkMalonSkel_cannon_mesh_layer_Opaque_tri_5[];
extern Vtx gMilkMalonSkel_waist_L_mesh_layer_Opaque_vtx_0[5];
extern Gfx gMilkMalonSkel_waist_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_waist_L_mesh_layer_Opaque_vtx_1[27];
extern Gfx gMilkMalonSkel_waist_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_thigh_L_mesh_layer_Opaque_vtx_0[39];
extern Gfx gMilkMalonSkel_thigh_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_thigh_L_mesh_layer_Opaque_vtx_1[62];
extern Gfx gMilkMalonSkel_thigh_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_shin_L_mesh_layer_Opaque_vtx_0[19];
extern Gfx gMilkMalonSkel_shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_shin_L_mesh_layer_Opaque_vtx_1[14];
extern Gfx gMilkMalonSkel_shin_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_foot_L_mesh_layer_Opaque_vtx_0[30];
extern Gfx gMilkMalonSkel_foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_foot_L_mesh_layer_Opaque_vtx_1[11];
extern Gfx gMilkMalonSkel_foot_L_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_waist_R_mesh_layer_Opaque_vtx_0[4];
extern Gfx gMilkMalonSkel_waist_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_waist_R_mesh_layer_Opaque_vtx_1[29];
extern Gfx gMilkMalonSkel_waist_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_thigh_R_mesh_layer_Opaque_vtx_0[45];
extern Gfx gMilkMalonSkel_thigh_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_thigh_R_mesh_layer_Opaque_vtx_1[73];
extern Gfx gMilkMalonSkel_thigh_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_shin_R_mesh_layer_Opaque_vtx_0[22];
extern Gfx gMilkMalonSkel_shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_shin_R_mesh_layer_Opaque_vtx_1[13];
extern Gfx gMilkMalonSkel_shin_R_mesh_layer_Opaque_tri_1[];
extern Vtx gMilkMalonSkel_foot_R_mesh_layer_Opaque_vtx_0[30];
extern Gfx gMilkMalonSkel_foot_R_mesh_layer_Opaque_tri_0[];
extern Vtx gMilkMalonSkel_foot_R_mesh_layer_Opaque_vtx_1[12];
extern Gfx gMilkMalonSkel_foot_R_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gMilkMalonSkel_ab_armour_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_cow_skin_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_SFWchest_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_skin_001_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_080_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_079_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_eyes_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_mouth_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_078_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_081_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_082_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_083_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_belt_001_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_tip_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_handle_wood_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_base_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_039_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_040_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_041_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_038_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_metal_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_handle_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_042_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_inner_barrel_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_044_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_f3dlite_material_043_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_outfit_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_back_armour_layerOpaque[];
extern Gfx mat_gMilkMalonSkel_shoes_layerOpaque[];
extern Gfx gMilkMalonSkel_root_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_middle_back_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_booba_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_booba_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_head_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_shoulder_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_upper_arm_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_forearm_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_hand_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_hammer_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_shoulder_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_upper_arm_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_forearm_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_hand_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_cannon_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_waist_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_thigh_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_shin_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_foot_L_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_waist_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_thigh_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_shin_R_mesh_layer_Opaque[];
extern Gfx gMilkMalonSkel_foot_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gMilkMalonSkel;
#define GMILKMALONSKEL_ROOT_POS_LIMB 0
#define GMILKMALONSKEL_ROOT_ROT_LIMB 1
#define GMILKMALONSKEL_MIDDLE_BACK_LIMB 2
#define GMILKMALONSKEL_BOOBA_L_LIMB 3
#define GMILKMALONSKEL_BOOBA_R_LIMB 4
#define GMILKMALONSKEL_HEAD_LIMB 5
#define GMILKMALONSKEL_SHOULDER_L_LIMB 6
#define GMILKMALONSKEL_UPPER_ARM_L_LIMB 7
#define GMILKMALONSKEL_FOREARM_L_LIMB 8
#define GMILKMALONSKEL_HAND_L_LIMB 9
#define GMILKMALONSKEL_HAMMER_LIMB 10
#define GMILKMALONSKEL_SHOULDER_R_LIMB 11
#define GMILKMALONSKEL_UPPER_ARM_R_LIMB 12
#define GMILKMALONSKEL_FOREARM_R_LIMB 13
#define GMILKMALONSKEL_HAND_R_LIMB 14
#define GMILKMALONSKEL_CANNON_LIMB 15
#define GMILKMALONSKEL_WAIST_L_LIMB 16
#define GMILKMALONSKEL_THIGH_L_LIMB 17
#define GMILKMALONSKEL_SHIN_L_LIMB 18
#define GMILKMALONSKEL_FOOT_L_LIMB 19
#define GMILKMALONSKEL_WAIST_R_LIMB 20
#define GMILKMALONSKEL_THIGH_R_LIMB 21
#define GMILKMALONSKEL_SHIN_R_LIMB 22
#define GMILKMALONSKEL_FOOT_R_LIMB 23
#define GMILKMALONSKEL_NUM_LIMBS 24
